version: 2
updates:
  - package-ecosystem: "github-actions" # Specify the ecosystem for GitHub Actions
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
      time: "11:48" # Runs at the start of every hour
